#!/bin/bash
set -e

sass () {
  npx node-sass "$@" bootstrap/custom.scss public/css/bootstrap.css
}

setup () {
  npm install
  if ! [ -d bootstrap/bootstrap-4.4.1 ]; then
    cd bootstrap
    curl -OL -o archive.zip https://github.com/twbs/bootstrap/archive/v4.4.1.zip
    unzip archive.zip
    rm archive.zip
  fi
  curl -o public/css/firebase-ui-auth-4.4.0.css https://www.gstatic.com/firebasejs/ui/4.4.0/firebase-ui-auth.css
  curl -o public/js/firebase-ui-auth-4.4.0.js https://www.gstatic.com/firebasejs/ui/4.4.0/firebase-ui-auth.js
}

dev () {
  sass
  clj -m cows.core
  overmind s
}

deploy () {
  sass
  clj -m cows.core
  rm -r $(find public/ -name cljs-runtime)
  npx shadow-cljs release main fn
  npx firebase deploy
}

"$@"
