#!/bin/bash
set -e

setup () {
  npm install live-server onchange
}

dev () {
  if ! [ -f public/index.html ]; then
    clj -m cows.core
  fi
  if [ "$1" = live ]; then
    (cd public && npx live-server) &
  else
    firebase serve &
  fi
  npx onchange -v 'src/**/*.clj' -- clj -m cows.core
}

"$@"
