#!/bin/bash
set -e

sass () {
  npx node-sass "$@" bootstrap/custom.scss public/css/bootstrap.css
}

setup () {
  npm install
  wget -O public/css/firebase-ui-auth-4.4.0.css https://www.gstatic.com/firebasejs/ui/4.4.0/firebase-ui-auth.css
  wget -O public/js/firebase-ui-auth-4.4.0.js https://www.gstatic.com/firebasejs/ui/4.4.0/firebase-ui-auth.js
  if ! [ -d bootstrap/bootstrap-4.4.1 ]; then
    cd bootstrap
    wget https://github.com/twbs/bootstrap/archive/v4.4.1.zip
    unzip v4.4.1.zip
    rm v4.4.1.zip
  fi
}

dev () {
  sass
  clj -m cows.core
  overmind s
}

deploy () {
  sass
  clj -m cows.core
  rm -rf $(find public/ -name cljs-runtime)
  npx shadow-cljs release main fn
  cp package.json functions/package.json
  npx firebase deploy
}

"$@"
